# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 07:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='snippet',
            managers=[
                ('with_votes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
