# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20160129_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
    ]
